# Generated by Django 2.2.1 on 2019-06-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BSeries',
            new_name='Series',
        ),
        migrations.DeleteModel(
            name='NewFolder',
        ),
    ]
