# Generated by Django 2.2.1 on 2019-05-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0002_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=30)),
                ('explanation', models.TextField(max_length=2000)),
                ('series_photo', models.ImageField(blank=True, default='no-img.jpg', upload_to='images/')),
                ('teacher', models.CharField(choices=[('da', 'Davod Vesaghati'), ('mo', 'mohammad khodayi'), ('ali', 'ali mohammadi')], default='da', max_length=2)),
            ],
        ),
    ]
